server:
  error:
    include-stacktrace: on_param #Esconde o stack tracer de errors apresentados no front-end

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


#useSSl - determinar se a comunicação com o banco de dados deve ser estabelecida por meio do protocolo SSL (Secure Sockets Layer) ou TLS (Transport Layer Security)
#O SSL/TLS é um protocolo de segurança criptografado que garante a confidencialidade e integridade dos dados transmitidos entre um cliente (aplicação) e um servidor (banco de dados).

#allowPublicKeyRetrieval é uma configuração usada em conexões de banco de dados para determinar se a recuperação de chaves públicas é permitida durante o processo de autenticação SSL/TLS pelo cliente.

